### ISSUE TITLE
crash when input has brackets without parentheses

### ISSUE THREAD

**Issue by Yoorkin** [markdown-it/markdown-it#1011]
```
# demo

array [1,2,3,4,5]

link [desc](github.com)

```

By running code below, I received error `Cannot read properties of undefined`. It seems like markdown-it recognized `[1,2,3,4,5]` as markdown link and tried to read the `()` part.

But in the [reference implementation](https://spec.commonmark.org/dingus/?text=%23%20demo%0A%0Aarray%20%5B1%2C2%2C3%2C4%2C5%5D%0A%0Alink%20%5Bdesc%5D(github.com)%0A%0A), the `[1,2,3,4,5]` is just a raw string in paragraph.

```
const MarkdownIt = require('markdown-it');
const content = `
  # demo
  
  array [1,2,3,4,5]
  
  link [desc](github.com)
`

const md = new MarkdownIt();
md.parse(content);
```

```
/Users/yorkin/source/markdown-linter/node_modules/.pnpm/markdown-it@14.0.0/node_modules/markdown-it/dist/index.cjs.js:4201
    if (typeof state.env.references === 'undefined') {
                         ^

TypeError: Cannot read properties of undefined (reading 'references')
    at Array.link (/Users/yorkin/source/markdown-linter/node_modules/.pnpm/markdown-it@14.0.0/node_modules/markdown-it/dist/index.cjs.js:4201:26)
    at ParserInline.tokenize (/Users/yorkin/source/markdown-linter/node_modules/.pnpm/markdown-it@14.0.0/node_modules/markdown-it/dist/index.cjs.js:4796:22)
    at ParserInline.parse (/Users/yorkin/source/markdown-linter/node_modules/.pnpm/markdown-it@14.0.0/node_modules/markdown-it/dist/index.cjs.js:4825:8)
    at Array.inline (/Users/yorkin/source/markdown-linter/node_modules/.pnpm/markdown-it@14.0.0/node_modules/markdown-it/dist/index.cjs.js:1386:23)
    at Core.process (/Users/yorkin/source/markdown-linter/node_modules/.pnpm/markdown-it@14.0.0/node_modules/markdown-it/dist/index.cjs.js:1846:13)
    at MarkdownIt.parse (/Users/yorkin/source/markdown-linter/node_modules/.pnpm/markdown-it@14.0.0/node_modules/markdown-it/dist/index.cjs.js:5456:13)
    at Object.<anonymous> (/Users/yorkin/source/markdown-linter/index.js:11:4)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)

Node.js v21.6.0
```

**Comment by puzrin** [comment]
You missed second mandatory param of parse.
