### ISSUE TITLE
The `punycode` module is deprecated. Please use a userland alternative instead

### ISSUE THREAD

**Issue by n-rodriguez** [markdown-it/markdown-it#1065]
Hi there!

I got this warning when compiling my assets with Webpack :

```sh
(node:26760) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:114:7)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1100:17)
    at require$$0.Module._load (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18281:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/markdown-it-npm-13.0.2-4aeddbcb85-4f48271bbd.zip/node_modules/markdown-it/lib/index.js:14:20)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18433:33)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1128:12)
    at require$$0.Module._load (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18281:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/markdown-it-npm-13.0.2-4aeddbcb85-4f48271bbd.zip/node_modules/markdown-it/index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18433:33)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1128:12)
    at require$$0.Module._load (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18281:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/modernizr-npm-3.13.1-975efeb3d1-366509b98e.zip/node_modules/modernizr/lib/metadata.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18433:33)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1128:12)
    at require$$0.Module._load (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18281:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/modernizr-npm-3.13.1-975efeb3d1-366509b98e.zip/node_modules/modernizr/lib/build.js:144:18)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18433:33)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1128:12)
    at require$$0.Module._load (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18281:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/modernizr-npm-3.13.1-975efeb3d1-366509b98e.zip/node_modules/modernizr/lib/cli.js:4:10)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18433:33)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1128:12)
    at require$$0.Module._load (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18281:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-modernizr-loader-virtual-10aaa4d415/0/cache/webpack-modernizr-loader-https-d6ff1859da-6d77a7edb6.zip/node_modules/webpack-modernizr-loader/index.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18433:33)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1128:12)
    at require$$0.Module._load (/Users/nicolas/PROJECTS/CONCERTO/concerto/.pnp.cjs:18281:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at loadLoader (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/loader-runner-npm-4.3.0-9ca67df372-555ae00286.zip/node_modules/loader-runner/lib/loadLoader.js:19:17)
    at iteratePitchingLoaders (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/loader-runner-npm-4.3.0-9ca67df372-555ae00286.zip/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/loader-runner-npm-4.3.0-9ca67df372-555ae00286.zip/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule._doBuild (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/NormalModule.js:963:3)
    at NormalModule.build (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/NormalModule.js:1148:15)
    at /Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/Compilation.js:1418:12
    at NormalModule.needBuild (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/NormalModule.js:1470:32)
    at Compilation._buildModule (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/Compilation.js:1399:10)
    at /Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/util/AsyncQueue.js:324:10
    at Hook.eval [as callAsync] (eval at create (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-1769336dd2.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/util/AsyncQueue.js:314:26)
    at AsyncQueue._ensureProcessing (/Users/nicolas/PROJECTS/CONCERTO/concerto/.yarn/__virtual__/webpack-virtual-623a76d944/0/cache/webpack-npm-5.95.0-19656f7d80-0377ad3a55.zip/node_modules/webpack/lib/util/AsyncQueue.js:301:12)
    at process.processImmediate (node:internal/timers:491:21)
```

**Comment by daedam** [comment]
I'm seeing this issue as well after upgrading to Node.js 22. It doesn't appear to be happening on Node 20.

**Comment by n-rodriguez** [comment]
> I'm seeing this issue as well after upgrading to Node.js 22. It doesn't appear to be happening on Node 20.

correct 👍

**Comment by Bayheck** [comment]
I encountered the same issue

**Comment by mattkrick** [comment]
markdown-it uses punycode.js, which would not show this warning.
punycode is bundled into node, so your lockfile doesn't tell the whole story, just like it doesn't include `fs` or `node:fs` as a dependency.
Instead, try searching for `punycode` or `require('punycode')` in your node_modules dir.
In my case, it was an old version of node-fetch that was using it.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/issues/1065#issuecomment-3618854472

As been said, ensure to use last library version. It use extermal punycode and will not cause warnings https://github.com/markdown-it/markdown-it/blob/cdb89ad5bce40dce8791e55acf3a2ec373a22801/package.json#L52

**Comment by n-rodriguez** [comment]
> As been said, ensure to use last library version. It use extermal punycode and will not cause warnings

it doesn't work :

```sh
Building packs: node_version=v24.14.0 node_env=development building_release=false
(node:84655) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:84655) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

```diff
diff --git a/package.json b/package.json
index 0ae2bceda..9cd00ac2c 100644
--- a/package.json
+++ b/package.json
@@ -81,6 +81,7 @@
     "postcss-import": "^16.1.1",
     "postcss-loader": "^8.2.1",
     "postcss-preset-env": "^11.3.0",
+    "punycode.js": "^2.3.1",
     "raty-js": "^4.3.0",
     "resolve-url-loader": "^5.0.0",
     "sass": "1.79.6",
```

**Comment by puzrin** [comment]
IMHO, that's something local for your application, not a package issue. You can create a minimalistic test repo to check.
