### ISSUE TITLE
TypeError: this.renderer is undefined after calling `md.render` inside a wrapper function

### ISSUE THREAD

**Issue by mrakow** [markdown-it/markdown-it#247]
## How the error occured

When executing the following code, a type error is thrown.

executed file:
```javascript
var md = require('markdown-it')();

function fancyLog (srcString, transformFunction) {
  console.log(transformFunction(srcString));
}

console.log(md.render('This one *works*.'));
fancyLog('This one **does not**', md.render);
```

Console output & stack trace (`<path-to-project>` used instead of real full path)
```bash
$ node index.js
<p>This one <em>works</em>.</p>
<path-to-project>/node_modules/markdown-it/lib/index.js:539
  return this.renderer.render(this.parse(src, env), this.options, env);
             ^

TypeError: Cannot read property 'renderer' of undefined
    at MarkdownIt.render (<path-to-project>/node_modules/markdown-it/lib/index.js:539:14)
    at fancyLog (<path-to-project>/index.js:4:15)
    at Object.<anonymous> (<path-to-project>/index.js:8:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

## Expected behaviour

`md.render` takes a string as parameter and outputs a string, transforming markdown into html. It does not matter whether `md.render` is called directly or given to function as a parameter.

## Actual behaviour

`md.render` works fine when called directly, but fails when calling it in a wrapper function (see above).

## Version info
markdown-it: v6.0.2
node: v5.2.0

**Comment by puzrin** [comment]
That's normal JS behaviour. You should wrap `.render()` call or bind function prior to pass:

```js
function transform(params...) {
  md.render(params...);
}
```

or

```js
var md = require('markdown-it')();

function fancyLog (srcString, transformFunction) {
  console.log(transformFunction(srcString));
}

fancyLog('This one **does not**', md.render.bind(md));
```
