### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'xhtmlOut' of undefined

### ISSUE THREAD

**Issue by yusiwen** [markdown-it/markdown-it#311]
When I render one of my markdown files, I got this error:

```
Unhandled rejection TypeError: Cannot read property 'xhtmlOut' of undefined
    at Renderer.renderToken (I:\git\jingo\node_modules\.8.2.1@markdown-it\lib\renderer.js:222:37)
    at Object.default_rules.image (I:\git\jingo\node_modules\.8.2.1@markdown-it\lib\renderer.js:100:14)
    at Renderer.renderInline (I:\git\jingo\node_modules\.8.2.1@markdown-it\lib\renderer.js:271:28)
    at Renderer.render (I:\git\jingo\node_modules\.8.2.1@markdown-it\lib\renderer.js:324:22)
    at Array.<anonymous> (I:\git\jingo\node_modules\.4.1.1@markdown-it-toc-and-anchor\dist\index.js:85:49)
    at Core.process (I:\git\jingo\node_modules\.8.2.1@markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (I:\git\jingo\node_modules\.8.2.1@markdown-it\lib\index.js:519:13)
    at MarkdownIt.render (I:\git\jingo\node_modules\.8.2.1@markdown-it\lib\index.js:539:36)
    at Object.render (I:\git\jingo\lib\renderer.js:152:15)
    at I:\git\jingo\routes\wiki.js:90:27
    at tryCatcher (I:\git\jingo\node_modules\.2.11.0@bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (I:\git\jingo\node_modules\.2.11.0@bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (I:\git\jingo\node_modules\.2.11.0@bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (I:\git\jingo\node_modules\.2.11.0@bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (I:\git\jingo\node_modules\.2.11.0@bluebird\js\main\async.js:123:16)
    at Async._drainQueues (I:\git\jingo\node_modules\.2.11.0@bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (I:\git\jingo\node_modules\.2.11.0@bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

This is my setting:

```JavaScript
var md = new MarkdownIt({
  html: false,
  xhtmlOut: false,
  highlight: function (code, lang) {
    lang = lang || "text";
    return Nsh.highlight(code, Nsh.getLanguage(lang) || Nsh.getLanguage("text"), {gutter: lang !== "text"});
  }
}).use(require("markdown-it-footnote"))
  .use(require("markdown-it-task-lists"), {enabled: false});
```

Don't know what/where to look at. Please help.  Thanks.

**Comment by yusiwen** [comment]
Oh, this is the markdown file causing trouble.
[Troublesome-markdown.zip](https://github.com/markdown-it/markdown-it/files/644642/Troublesome-markdown.zip)

**Comment by puzrin** [comment]
Could you narrow down code and test sqample? For example, remove `.use()` and reduce sample size...

**Comment by yusiwen** [comment]
@puzrin 
Thanks for your advice. I've found the problem.
