### ISSUE TITLE
Cannot read property 'references' of undefined ()

### ISSUE THREAD

**Issue by 1000ch** [markdown-it/markdown-it#472]
Found an error when I use markdown-it in [markdown-headings](https://github.com/1000ch/markdown-headings).

```sh
TypeError: Cannot read property 'references' of undefined
    at Array.link (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/node_modules/markdown-it/lib/rules_inline/link.js:101:26)
    at ParserInline.tokenize (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/node_modules/markdown-it/lib/parser_inline.js:135:22)
    at ParserInline.parse (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/node_modules/markdown-it/lib/parser_inline.js:163:8)
    at Array.inline (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/node_modules/markdown-it/lib/rules_core/inline.js:11:23)
    at Core.process (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/node_modules/markdown-it/lib/index.js:523:13)
    at module.exports.arg (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/index.js:14:29)
    at Promise.all.texts.map.text (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/cli.js:18:48)
    at Array.map (<anonymous>)
    at globby.then.then.then.texts (/Users/1000ch/workspace/github.com/1000ch/markdown-headings/cli.js:18:36)
```

`env` (argument of `ParserInline.prototype.parse`) is `undefined` on some conditions.

**Comment by 1000ch** [comment]
I executed `node cli.js ../**/*.md` on cloned markdown-headings repo.

**Comment by puzrin** [comment]
Please use minimal reproducible sample, restricted to this package only.

Looks you missed second mandatory param in `.parse()` / `.parseInline()` call.
