### ISSUE TITLE
Docs suggest MarkdownIt.parse's env parameter is optional

### ISSUE THREAD

**Issue by DavidAnson** [markdown-it/markdown-it#64]
See: https://markdown-it.github.io/markdown-it/#MarkdownIt.parse

The env parameter appears to be defaulted to "{}" for render and renderInline, but not for parse. Without passing {} as env to parse, I find that it attempts to dereference null for the following input:

> Go to (this website)[http://www.example.com]

**Comment by DavidAnson** [comment]
TypeError: Cannot read property 'references' of undefined
    at Array.link (demo\node_modules\markdown-it\lib\rules_inline\link.js:93:25)
    at ParserInline.tokenize (demo\node_modules\markdown-it\lib\parser_inline.js:126:22)
    at ParserInline.parse (demo\node_modules\markdown-it\lib\parser_inline.js:153:8)
    at Array.inline (demo\node_modules\markdown-it\lib\rules_core\inline.js:10:23)
    at Core.process (demo\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (demo\node_modules\markdown-it\lib\index.js:382:13)

**Comment by puzrin** [comment]
Yes. It's mandatory param for parse, because it can return some data there.

**Comment by DavidAnson** [comment]
The documentation I link to says "{} by default" and "You will not need it with high probability.". That sounds optional - it's actually the same language used for the render method where env IS optional. I'm not suggesting a code change, but I think a change to the documentation might help make this more clear to others. Thanks!

**Comment by puzrin** [comment]
Ah! Got it. Thanks for clarification

Commited fix. Web doc will be updated on nearest release, very soon.
