### ISSUE TITLE
Cannot read property 'breaks' of undefined

### ISSUE THREAD

**Issue by yves-chevallier** [markdown-it/markdown-it#712]
I would like to do the parsing in three steps 

1. Get the tokens, 
2. process the tokens, 
3. render into HTML

With the following example, I get into an issue

```js
var md = require("markdown-it")();
var Renderer = require("markdown-it/lib/renderer");
let renderer = new Renderer()

markdown = `line1
line2
`

tokens = md.parse(markdown)
html = renderer.render(tokens)
console.log(html)
```

Error

```
TypeError: Cannot read property 'breaks' of undefined
    at Object.default_rules.softbreak (/home/canard/chevallier.io/node_modules/markdown-it/lib/renderer.js:108:18)
    at Renderer.renderInline (/home/canard/chevallier.io/node_modules/markdown-it/lib/renderer.js:271:28)
    at Renderer.render (/home/canard/chevallier.io/node_modules/markdown-it/lib/renderer.js:324:22)
    at Object.<anonymous> (/home/canard/chevallier.io/test.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

It seems the default `options` are not sent to the `renderer` but with the following it works

```
var options = {
  html:         false,        // Enable HTML tags in source
  xhtmlOut:     false,        // Use '/' to close single tags (<br />).
                              // This is only for full CommonMark compatibility.
  breaks:       false,        // Convert '\n' in paragraphs into <br>
  langPrefix:   'language-',  // CSS language prefix for fenced blocks. Can be
                              // useful for external highlighters.
  linkify:      false,        // Autoconvert URL-like text to links
  typographer:  false,
  quotes: '“”‘’',
  highlight: function (/*str, lang*/) { return ''; }
}
html = renderer.render(tokens, options)
```

It is the normal behavior and it is possible to simply get the renderer from `md` such as `md.getRenderer().render(tokens)`?

**Comment by yves-chevallier** [comment]
Well... I think I got it 

```
var md = require("markdown-it")();

markdown = `line1
line2
`

tokens = md.parse(markdown)
html = md.renderer.render(tokens, md.options)
console.log(html)
```
