### ISSUE TITLE
all dataclasses in markdown_it throw errors when a different dependency tries to import it

### ISSUE THREAD

**Issue by DougStoker** [markdown-it/markdown-it#923]
Traceback (most recent call last):
  File "/Users/doug/Documents/diffusion/kohya_ss/kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/gradio/components.py", line 28, in <module>
    from markdown_it import MarkdownIt
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/__init__.py", line 5, in <module>
    from .main import MarkdownIt
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/main.py", line 7, in <module>
    from . import helpers, presets  # noqa F401
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/helpers/__init__.py", line 5, in <module>
    from .parse_link_label import parseLinkLabel
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/helpers/parse_link_label.py", line 8, in <module>
    from markdown_it.rules_inline import StateInline
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/rules_inline/__init__.py", line 17, in <module>
    from . import emphasis, strikethrough
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/rules_inline/emphasis.py", line 4, in <module>
    from .state_inline import Delimiter, StateInline
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/rules_inline/state_inline.py", line 10, in <module>
    from ..ruler import StateBase
  File "/Users/doug/.pyenv/versions/3.10.0a7/lib/python3.10/site-packages/markdown_it/ruler.py", line 55, in <module>
    @dataclass(**DATACLASS_KWARGS)
TypeError: dataclass() got an unexpected keyword argument 'slots'

**Comment by DougStoker** [comment]
i'll move this to the python repo, sorry
